### PR TITLE
Python example and the JSON grammar for number.

### PR DESCRIPTION
**Pull request by wahn**
I mentioned that typo on Gitter and was asked to create a PR.

### CODE REVIEW

**Comment by wahn** [comment]
One pull request for two checkins.

1. One thing I noticed in the official book: The Python code in non-atomic should read `print("`, not `print(f"` ... not a big thing, but it would fail with `SyntaxError: invalid syntax` if you would try to run it with **Python** ...
2. I'm also not sure about the number rule in writing the JSON grammar. Shouldn't it be `("." ~ ASCII_DIGIT+)?` instead of `("." ~ ASCII_DIGIT*)?`?

**Comment by wahn** [comment]
`Laurent Wandrebeck @lwandrebeck 12:13` @wahn : for example 1. is correct. + would indicate 1.at_least_one_number you’re correct about the official book, likely a typo
`Jan Walter @wahn 12:38` @lwandrebeck : About the JSON grammar: Then the diagram for `number` @ https://json.org seems wrong to me. Shouldn't the lines (after the `.`) bypassing `digit` be curved the other way then? Like they do for `. digit`?
`Jan Walter @wahn 12:45` On the same web page the rule for `digits` used in `frac` suggests to me that you either bypass `. digit` entirely, but if you use the `.` you need at least one digit.
`Laurent Wandrebeck @lwandrebeck 12:51` hmmm it looks like you’re right and pest grammar is not following perfectly json format for number. would you care opening issues for that ? (and even better propose a PR ? :))

**Comment by CAD97** [comment]
JSON _number_ is in fact a `+` and not a `*` after the `.`.

```
number
    int frac exp

int
    digit
    onenine digits
    '-' digit
    '-' onenine digits

digits
    digit
    digit digits

digit
    '0'
    onenine

onenine
    '1' .. '9'

frac
    ""
    '.' digits

exp
    ""
    'E' sign digits
    'e' sign digits

sign
    ""
    '+'
    '-'
```

**Comment by CAD97** [comment]
However, the f-string is indeed valid Python 3.6+:

https://tio.run/##K6gsycjPM/7/v6AoM69EI00pJCNVITGvuDy1SCGzWKHaSEFbwaRWT0nz/38A  
https://www.python.org/dev/peps/pep-0498/

**Comment by dragostis** [comment]
@CAD97, should we only keep the JSON fix?

**Comment by wahn** [comment]
Maybe you could add a note about the validity of the syntax for `f"...'` from Python 3.6+ onwards. Otherwise it might confuse others as well. It's not valid for Python 3.x in general.

**Comment by CAD97** [comment]
The example needs to be an f-string anyway in order to make sense: it's the f-string that makes you want to emit rules in the middle of the atomic string. I could see a note about this requiring python 3.6, though.

I'm r+ on the json grammar fix, though.

**Pull request closed without merging**
